import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { BottomNavigation, Button } from '@mui/material'
import { useSession, signIn, signOut } from "next-auth/react";


export default function Home() {
    const { data: session } = useSession()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <BottomNavigation>
              {
                  !session ? (<Button onClick={signIn} variant="contained">Login</Button>) : (<Button onClick={signOut} variant="outlined">Sign Out</Button>)
              }
          </BottomNavigation>
      </main>
    </>
  )
}
